apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: netflix:/Service:default/netflix-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"netflix:/Service:default/netflix-service"},"labels":{"app":"netflix","project":"devsecops-netflix"},"name":"netflix-service","namespace":"default"},"spec":{"ports":[{"name":"http","nodePort":30080,"port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"netflix"},"type":"NodePort"}}
  creationTimestamp: "2026-09-04T19:32:29Z"
  labels:
    app: netflix
    project: devsecops-netflix
  name: netflix-service
  namespace: default
  resourceVersion: "10181"
  uid: 9be5599b-eaf7-4603-9f5d-9e7eb5ac3ca6
spec:
  clusterIP: 10.96.178.227
  clusterIPs:
  - 10.96.178.227
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: netflix
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
